# Generated by Django 4.1.1 on 2022-09-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.TextField(max_length=100, null=True, verbose_name='Двигатель')),
                ('hp', models.IntegerField(max_length=1000, null=True, verbose_name='Лошадиные силы')),
                ('nm', models.IntegerField(max_length=1000, null=True, verbose_name='Ньютон метр')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
    ]
