# Generated by Django 4.1.1 on 2022-10-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('engine', models.TextField(max_length=100, verbose_name='Двигатель')),
                ('hp', models.CharField(max_length=1000, verbose_name='Лошадиные силы')),
                ('nm', models.CharField(max_length=1000, verbose_name='Ньютон метр')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('series', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.TextField(max_length=100, null=True, verbose_name='Двигатель')),
                ('hp', models.IntegerField(max_length=1000, null=True, verbose_name='Лошадиные силы')),
                ('nm', models.IntegerField(max_length=1000, null=True, verbose_name='Ньютон метр')),
                ('series', models.TextField(max_length=500, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ModelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=500)),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_comment', to='models.model')),
            ],
        ),
    ]
