# Generated by Django 4.1.1 on 2022-10-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbrand',
            name='comments',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
