# Generated by Django 4.1.1 on 2022-09-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_image'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='model',
            name='series',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand'),
        ),
    ]
