# Generated by Django 4.1.1 on 2022-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='engine',
            field=models.TextField(max_length=100, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='brand',
            name='hp',
            field=models.IntegerField(max_length=1000, null=True, verbose_name='Лошадиные силы'),
        ),
        migrations.AddField(
            model_name='brand',
            name='nm',
            field=models.IntegerField(max_length=1000, null=True, verbose_name='Ньютон метр'),
        ),
        migrations.AddField(
            model_name='brand',
            name='series',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=' '),
        ),
    ]
