# Generated by Django 4.1.1 on 2022-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_engine_brand_hp_brand_nm_brand_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='engine',
            field=models.CharField(max_length=100, null=True, verbose_name='Двигатель'),
        ),
    ]
