# Generated by Django 4.1.1 on 2022-09-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='nm',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='series',
        ),
    ]
